### ISSUE TITLE
Latest image is broken

### ISSUE THREAD

**Issue by derekirish3** [nottirb/base-builders#2]
There appears to be a compiler error in the current nightly rust build. Might suggest switching to an older version like `ghcr.io/nottirb/fuzz-rust@sha256:85ce0c47246b8ecdd4e3889a4964445d555406d53bbf9b99f3c833ac3a6446b6`

You can do this as follows:

```
docker pull ghcr.io/nottirb/fuzz-rust@sha256:85ce0c47246b8ecdd4e3889a4964445d555406d53bbf9b99f3c833ac3a6446b6
docker tag ghcr.io/nottirb/fuzz-rust@sha256:85ce0c47246b8ecdd4e3889a4964445d555406d53bbf9b99f3c833ac3a6446b6 ghcr.io/nottirb/fuzz-rust:latest
docker push ghcr.io/nottirb/fuzz-rust:latest
```

**Comment by nottirb** [comment]
Hopefully this is fixed now, if not let me know and I can revert and stop workflows. Sorry for the late reply.

Closing for now.
